Repository PedroChaparro/loomies-backend, pull requests merged in 2023-04, with the labels that each got.

#83 Refactor: User collection and Improve naming.
  api/configuration/configuration.go
  api/controllers/gyms.go
  api/controllers/items.go
  api/controllers/loomies.go
  api/controllers/session.go
  api/controllers/user.go
  api/controllers/websocket.go
  api/controllers/zones.go
  api/interfaces/interfaces.go
  api/models/collections.go
  api/models/loomies.go
  api/models/user.go
  api/models/zones.go
  api/routes/router.go
  api/utils/email.go
  api/utils/helpers.go
  api/utils/token.go
Labels: enhancement, backend

#81 Feat: Get loomie team
  .github/docs/openapi.yml
  api/controllers/user.go
  api/routes/router.go
Labels: backend, loomie inventory

#85 Fix: Outdated loomies
  algorithms/backups/README.md
  algorithms/database/cronjobs/README.md
  algorithms/database/package.json
  api/.env.example
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/models/loomies.go
Labels: backend, loomie inventory

#79 Feat: Fuse loomies
  .github/docs/openapi.yml
  algorithms/database/models/mongoose.js
  api/.env.example
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/loomies.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/interfaces/responses.go
  api/models/collections.go
  api/models/gyms.go
  api/models/items.go
  api/models/loom_balls.go
  api/models/loomies.go
  api/models/user.go
  api/models/zones.go
  api/routes/router.go
  api/utils/helpers.go
Labels: backend, loomie inventory

#92 Fix: Schemas
  algorithms/database/models/mongoose.js
  api/controllers/gyms.go
Labels: bug, enhancement, backend

#88 Docs: Entity relationship diagram
  .github/docs/database/ENTITY_RELATIONSHIP_DIAGRAM.md
  .github/docs/database/ENTITY_RELATIONSHIP_DIAGRAM.svg
Labels: documentation, backend

#77 Endpoint to catch a loomie
  .github/docs/openapi.yml
  api/controllers/loomies.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/loomies.go
  api/models/user.go
  api/routes/router.go
  api/utils/helpers.go
Labels: backend, loomie inventory

#86 Test: Add missing user endpoints tests
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/session_test.go
  api/controllers/user.go
  api/controllers/user_test.go
  api/tests/tests_utils.go
  api/utils/email.go
  api/utils/helpers.go
Labels: backend

#94 Fix: Adding id field in Gyms Info
  api/interfaces/interfaces.go
Labels: bug

#91 Feat: Update loomie team
  .github/docs/openapi.yml
  api/controllers/loomies.go
  api/controllers/user.go
  api/controllers/websocket.go
  api/interfaces/requests.go
  api/models/user.go
  api/routes/router.go
Labels: backend, battle, loomie inventory

#95 Test: Gyms endpoints
  api/controllers/gyms.go
  api/controllers/gyms_test.go
  api/controllers/user_test.go
  api/tests/tests_utils.go
Labels: backend, CI

#96 Test: Items endpoints
  api/controllers/items.go
  api/controllers/items_test.go
Labels: backend, CI

#93 Feat: Combat attacks
  api/.env.example
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/helpers.go
  api/combat/interfaces.go
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/websocket.go
  api/interfaces/interfaces.go
  api/main.go
  api/models/collections.go
  api/models/loomies.go
  api/models/user.go
  api/models/zones.go
  api/utils/helpers.go
  api/utils/token.go
Labels: backend, battle

#99 Chore: Update items descriptions
  data/items.json
Labels: backend, item inventory

#101 Feat: Multiple gyms
  algorithms/database/bulk.js
  algorithms/database/models/mongoose.js
  algorithms/database/utils/utils.js
  api/interfaces/interfaces.go
  api/models/zones.go
  data/places.json
  data/static_places.json
Labels: backend, gymnasium

#102 Feat: Endpoint to use an item from inventory (out of combat)
  .github/docs/openapi.yml
  api/controllers/items.go
  api/controllers/items_test.go
  api/interfaces/requests.go
  api/models/items.go
  api/models/loomies.go
  api/models/user.go
  api/routes/router.go
Labels: backend, battle, item inventory, loomie inventory

#103 Feat: Give all loomies (Debug script)
  algorithms/database/debug/README.md
  algorithms/database/debug/giveLoomies.js
  algorithms/database/models/mongoose.js
  algorithms/database/package.json
  algorithms/database/utils/utils.js
Labels: enhancement, backend, loomie inventory

#106 Fix: Adjustments
  api/controllers/loomies.go
  api/main.go
  api/models/loomies.go
  api/models/zones.go
  api/utils/helpers.go
  data/loomballs.json
  data/loomies_rarities.json
Labels: backend, item inventory, loomie inventory

#110 Fix: Combat
  api/combat/MESSAGES_TYPES.md
  api/combat/interfaces.go
  api/controllers/websocket.go
Labels: bug, backend, battle

#111 Fix: Ignore captured loomies
  api/controllers/loomies.go
  api/models/loomies.go
Labels: bug, backend, geolocation, loomie inventory

#112 Feat(combat): Change player loomie
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/interfaces.go
Labels: backend, battle

#116 Fix: Gyms protectors lvl
  algorithms/database/utils/utils.js
Labels: backend, battle, gymnasium

#105 Create LICENSE
  LICENSE
Labels: backend

#115 Escape from combat
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/interfaces.go
Labels: backend, battle

#119 Fix: Websocket send message as JSON instead of string
  api/combat/interfaces.go
Labels: backend, battle

#117 Feat: register battle changes
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/helpers.go
  api/models/gyms.go
  api/models/loomies.go
Labels: backend, battle, gymnasium

#114 Fix: Gyms challenge timeout
  api/.env.example
  api/combat/interfaces.go
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/websocket.go
  api/interfaces/interfaces.go
  api/models/collections.go
  api/models/gyms.go
  api/models/user.go
Labels: backend, battle

#120 Fix: Combat issues
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/helpers.go
  api/controllers/gyms.go
  api/controllers/websocket.go
  api/interfaces/interfaces.go
  api/models/gyms.go
Labels: bug, battle, gymnasium, item inventory, loomie inventory

#122 Release: v0.2.0 (Backend)
  algorithms/database/utils/utils.js
  api/.env.example
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/helpers.go
  api/combat/interfaces.go
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/gyms.go
  api/controllers/items.go
  api/controllers/loomies.go
  api/controllers/websocket.go
  api/interfaces/combat.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/collections.go
  api/models/gyms.go
  api/models/items.go
  api/models/loomies.go
  api/models/user.go
Labels: backend, CD

#126 Feat: Update gym protectors
  .github/docs/openapi.yml
  api/controllers/gyms.go
  api/interfaces/requests.go
  api/models/gyms.go
  api/models/user.go
  api/routes/router.go
Labels: backend, gymnasium

#97 Test: Loomies endpoints
  .github/docs/openapi.yml
  .github/workflows/integration.yml
  api/.env.example
  api/controllers/gyms_test.go
  api/controllers/loomies.go
  api/controllers/loomies_test.go
  api/safely_run_tests.sh
Labels: backend, CI
