Repository PedroChaparro/loomies-backend, pull requests merged in 2023-02, with the labels that each got.

#29 Feat: Gyms Generation and Insertion
  .gitignore
  algorithms/gyms_generation/README.md
  algorithms/gyms_generation/go.mod
  algorithms/gyms_generation/go.sum
  algorithms/gyms_generation/main.go
  algorithms/gyms_generation/utils/utils.go
  algorithms/gyms_insertion/.env.example
  algorithms/gyms_insertion/README.md
  algorithms/gyms_insertion/bulk.js
  algorithms/gyms_insertion/package.json
  data/places.json
  data/zones.json
Labels: backend, gymnasium

#30 Feat: CD
  .github/workflows/deployment.yml
  api/.dockerignore
  api/Dockerfile
Labels: backend, CD

#33 Endpoint for user account creation
  api/controllers/user.go
  api/go.mod
  api/interfaces/init.go
  api/models/user.go
  api/routes/init.go
Labels: backend, Auth

#36 Test: Signup route
  .gitignore
  api/controllers/init.go
  api/controllers/user_test.go
  api/go.mod
  api/go.sum
  api/interfaces/interfaces.go
  api/models/init.go
  api/routes/router.go
Labels: backend, CI

#37 Feat: Automate backups
  .github/workflows/backup.yml
  algorithms/backups/backup.sh
Labels: backend

#35 Feat: Integration workflow
  .github/workflows/integration.yml
Labels: backend, CI

#41 feat: Add zones x,y coordinates as string
  algorithms/gyms_insertion/bulk.js
Labels: backend, gymnasium

#43 Refactor/login
  api/controllers/session.go
  api/controllers/user.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/user.go
  api/utils/token.go
Labels: backend, Auth

#42 Endpoint for login
  api/controllers/session.go
  api/controllers/user.go
  api/go.mod
  api/go.sum
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/user.go
  api/routes/router.go
  api/utils/token.go
Labels: backend, Auth

#45 test/refactor: Test login route and refactor configuration.go file
  api/.env.example
  api/configuration/configuration.go
  api/controllers/session_test.go
  api/controllers/user_test.go
  api/interfaces/interfaces.go
  api/tests/tests_utils.go
  api/utils/token.go
Labels: backend

#51 Rebase / update development branch.
  .github/workflows/backup.yml
  .github/workflows/integration.yml
  algorithms/backups/backup.sh
Labels: CI

#53 Fix: #52 Mail shouldn't be case sensitive
  api/models/user.go
Labels: bug, backend, Auth

#48 Test: Refresh and Whoami
  api/controllers/session_test.go
  api/tests/tests_utils.go
Labels: backend, CI

#54 Fix: gyms generation
  algorithms/gyms_generation/main.go
  algorithms/gyms_generation/utils/utils.go
  data/places.json
  data/zones.json
Labels: enhancement, backend, gymnasium

#46 Endpoint to obtain near gyms
  .gitignore
  algorithms/gyms_insertion/bulk.js
  api/controllers/zones.go
  api/interfaces/interfaces.go
  api/models/zones.go
  api/routes/router.go
Labels: backend, geolocation, gymnasium

#57 Feat: database setup
  .gitignore
  algorithms/database_setup/.env.example
  algorithms/database_setup/README.md
  algorithms/database_setup/bulk.js
  algorithms/database_setup/bulk.test.js
  algorithms/database_setup/models/mongoose.js
  algorithms/database_setup/package.json
  algorithms/database_setup/utils/utils.js
  algorithms/gyms_insertion/bulk.js
  data/items.json
  data/loomies.json
  data/loomies_rarities.json
  data/loomies_types.json
Labels: backend, item inventory, loomie inventory
