Repository PedroChaparro/loomies-backend, pull requests merged in 2023-05, with the labels that each got.

#129 Get user loomies team in combat
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/interfaces.go
Labels: backend, battle, loomie inventory

#130 Fix: Populate wild loomies
  api/interfaces/interfaces.go
  api/models/collections.go
  api/models/loomies.go
Labels: bug, backend, loomie inventory

#131 Test: Controllers
  api/controllers/gyms.go
  api/controllers/gyms_test.go
  api/controllers/items.go
  api/controllers/items_test.go
  api/controllers/user.go
  api/controllers/user_test.go
  api/controllers/websocket.go
  api/controllers/websocket_test.go
  api/controllers/zones.go
  api/controllers/zones_test.go
Labels: backend, gymnasium, CI

#133 Fix: Gyms protectors busy state
  api/controllers/gyms.go
Labels: bug, backend, gymnasium

#127 Fix: Combat Issues III
  api/.env.example
  api/combat/handlers.go
  api/combat/interfaces.go
  api/controllers/websocket.go
Labels: bug, backend, battle

#134 Release 0.3.0 (Backend)
  .github/docs/database/ENTITY_RELATIONSHIP_DIAGRAM.md
  .github/docs/database/ENTITY_RELATIONSHIP_DIAGRAM.svg
  .github/docs/openapi.yml
  .github/workflows/integration.yml
  api/.env.example
  api/combat/MESSAGES_TYPES.md
  api/combat/handlers.go
  api/combat/helpers.go
  api/combat/interfaces.go
  api/controllers/gyms.go
  api/controllers/gyms_test.go
  api/controllers/items.go
  api/controllers/items_test.go
  api/controllers/loomies.go
  api/controllers/loomies_test.go
  api/controllers/user.go
  api/controllers/user_test.go
  api/controllers/websocket.go
  api/controllers/websocket_test.go
  api/controllers/zones.go
  api/controllers/zones_test.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/collections.go
  api/models/gyms.go
  api/models/loomies.go
  api/models/user.go
  api/routes/router.go
  api/safely_run_tests.sh
Labels: backend, CD
