Repository PedroChaparro/loomies-backend, pull requests merged in 2023-03, with the labels that each got.

#58 Feat: near loomies
  algorithms/database_setup/.env.example
  algorithms/database_setup/README.md
  algorithms/database_setup/bulk.js
  algorithms/database_setup/models/mongoose.js
  algorithms/database_setup/package.json
  algorithms/database_setup/wild_loomies_remover.js
  api/.env.example
  api/configuration/configuration.go
  api/controllers/loomies.go
  api/controllers/session.go
  api/controllers/user.go
  api/controllers/zones.go
  api/go.mod
  api/go.sum
  api/interfaces/interfaces.go
  api/models/loomies.go
  api/models/user.go
  api/models/zones.go
  api/routes/router.go
  api/utils/helpers.go
Labels: backend, geolocation, loomie inventory

#63 Ci: email validation
  .github/workflows/integration.yml
  api/.env.example
  api/utils/email.go
Labels: backend, CI

#61 Feat: Generate and Claim Gyms rewards
  algorithms/database/.env.example
  algorithms/database/README.md
  algorithms/database/bulk.js
  algorithms/database/bulk.test.js
  algorithms/database/cronjobs/README.md
  algorithms/database/cronjobs/remove_outdated_loomies/remove.js
  algorithms/database/cronjobs/update_gyms_rewards/helpers.js
  algorithms/database/cronjobs/update_gyms_rewards/update.js
  algorithms/database/models/mongoose.js
  algorithms/database/package.json
  algorithms/database/utils/utils.js
  algorithms/database_setup/package.json
  api/.env.example
  api/configuration/configuration.go
  api/controllers/gyms.go
  api/controllers/zones.go
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/interfaces/responses.go
  api/models/gyms.go
  api/models/items.go
  api/models/loom_balls.go
  api/models/user.go
  api/models/zones.go
  api/routes/router.go
  data/items.json
  data/loomballs.json
Labels: backend, gymnasium, item inventory

#64 Fix: Outlier Gym
  data/places.json
Labels: bug

#67 Feat: Default gyms "protectors"
  algorithms/database/bulk.js
  algorithms/database/models/mongoose.js
  algorithms/database/utils/utils.js
  api/interfaces/interfaces.go
Labels: backend, gymnasium, loomie inventory

#62 Feat/email validation
  .github/workflows/integration.yml
  api/.env.example
  api/controllers/user.go
  api/go.mod
  api/go.sum
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/models/user.go
  api/routes/router.go
  api/utils/email.go
  api/utils/helpers.go
Labels: backend, Auth

#44 ci: Setup database
  .github/workflows/integration.yml
Labels: backend, CI

#59 Get items user
  api/controllers/items.go
  api/interfaces/interfaces.go
  api/interfaces/responses.go
  api/models/items.go
  api/routes/router.go
Labels: backend, item inventory

#68 Fix: Claim rewards
  api/controllers/gyms.go
  api/models/user.go
Labels: bug, item inventory

#70 Endpoint to reset password
  api/controllers/user.go
  api/interfaces/interfaces.go
  api/models/user.go
  api/routes/router.go
Labels: backend, Auth

#74 Docs: Swagger
  .github/docs/openapi.yml
Labels: documentation, backend

#73 Refactor: Endpoints
  api/controllers/session_test.go
  api/controllers/user_test.go
  api/interfaces/responses.go
  api/routes/router.go
  api/tests/tests_utils.go
Labels: enhancement, backend

#69 Endpoint to obtain Loomies from an user
  api/controllers/items.go
  api/controllers/loomies.go
  api/controllers/session.go
  api/controllers/user.go
  api/interfaces/responses.go
  api/middlewares/middlewares.go
  api/models/user.go
  api/routes/router.go
Labels: backend, loomie inventory

#76 Fix: Get near loomies even if noone
  .github/docs/openapi.yml
  api/controllers/loomies.go
Labels: backend, geolocation, loomie inventory

#72 Feat: Initialize combat
  .github/docs/openapi.yml
  .github/docs/sequences/combat.md
  .github/workflows/integration.yml
  api/.env.example
  api/combat/handlers.go
  api/combat/interfaces.go
  api/configuration/configuration.go
  api/configuration/interfaces.go
  api/controllers/websocket.go
  api/go.mod
  api/go.sum
  api/interfaces/interfaces.go
  api/interfaces/requests.go
  api/main.go
  api/routes/websocket.go
  api/utils/helpers.go
  api/utils/token.go
Labels: backend, battle, gymnasium

#75 Endpoint validate if Loomie still exists
  .github/docs/openapi.yml
  api/controllers/loomies.go
  api/interfaces/requests.go
  api/models/loomies.go
  api/routes/router.go
Labels: backend, loomie inventory
